const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('gb', {
  call: (op, params, opts) => ipcRenderer.invoke('gbrain:call', op, params, opts),
  raw: (args, opts) => ipcRenderer.invoke('gbrain:raw', args, opts),
  init: () => ipcRenderer.invoke('gbrain:init'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: s => ipcRenderer.invoke('settings:set', s),
  metrics: () => ipcRenderer.invoke('metrics:get'),
  pickDir: () => ipcRenderer.invoke('dialog:pickDir'),
  pickFiles: () => ipcRenderer.invoke('dialog:pickFiles'),
  readText: p => ipcRenderer.invoke('fs:readText', p),
  pdfExtract: (p, maxPages) => ipcRenderer.invoke('pdf:extract', p, maxPages),
  openPath: p => ipcRenderer.invoke('shell:open', p),
  envCheck: () => ipcRenderer.invoke('env:check'),
  marketLatest: () => ipcRenderer.invoke('market:latest'),
  marketSync: () => ipcRenderer.invoke('market:sync'),
  marketFetch: sym => ipcRenderer.invoke('market:fetch', sym),
  onSyncLog: cb => ipcRenderer.on('market:sync:log', (_e, line) => cb(line)),
  watchlistGet: () => ipcRenderer.invoke('watchlist:get'),
  watchlistSet: l => ipcRenderer.invoke('watchlist:set', l),
  purge: type => ipcRenderer.invoke('brain:purge', type),
  ai: req => ipcRenderer.invoke('ai:chat', req),
  onAiChunk: cb => ipcRenderer.on('ai:chunk', (_e, p) => cb(p)),
});
